version: "2"

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - vendor
    - tests
  go: '1.23'

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: standard
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - gocyclo
    - gocognit
    - funlen
    - errname
    - gosec
    - bodyclose
    - prealloc
    - unconvert
    - dupl
    - misspell
    - revive

  exclusions:
    rules:
      - path: '_test\.go$'
        linters:
          - funlen
          - dupl
          - gosec
          - gocyclo
      - path: '^tests/'
        linters:
          - all

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  staticcheck:
    checks:
      - all
      - "-SA1019"
  
  govet:
    enable-all: true
  
  gocyclo:
    min-complexity: 15
  
  gocognit:
    min-complexity: 20
  
  funlen:
    lines: 80
    statements: 50
  
  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name
